"""
LifeData V4 — Media Module Parsers
modules/media/parsers.py

Parses Tasker-generated metadata CSVs for multimedia:
  - voice_meta_*.csv  → media.voice  (voice memos, dream journals)
  - photo_meta_*.csv  → media.photo  (photos with EXIF extraction)
  - video_meta_*.csv  → media.video  (video clips with ffprobe metadata)

Media files themselves are NOT loaded into the events table — only the
metadata, transcripts, and extracted features are stored as events.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
from pathlib import Path
from typing import Any

from core.event import Event
from core.logger import get_logger
from core.utils import parse_timestamp, safe_float, safe_json

# Regex for safe media IDs: alphanumeric, hyphens, underscores, dots only
_SAFE_MEDIA_ID_RE = re.compile(r"^[a-zA-Z0-9._-]+$")

log = get_logger("lifedata.media.parsers")

DEFAULT_TZ_OFFSET = "-0500"
PARSER_VERSION = "1.0.0"

# Try to import Pillow for EXIF — graceful if missing
try:
    from PIL import Image
    from PIL.ExifTags import GPSTAGS, TAGS
    HAS_PILLOW = True
except ImportError:
    HAS_PILLOW = False
    log.info("Pillow not available — EXIF extraction disabled")

# VADER for transcript sentiment — lazy loaded to avoid import-time blocking
_vader = None
HAS_VADER = False


def _get_vader() -> Any:
    """Lazy-load VADER sentiment analyzer."""
    global _vader, HAS_VADER
    if _vader is not None:
        return _vader
    try:
        from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
        _vader = SentimentIntensityAnalyzer()
        HAS_VADER = True
        return _vader
    except ImportError:
        HAS_VADER = False
        return None


def _is_safe_media_id(media_id: str) -> bool:
    """Validate that a media ID contains only safe characters.

    Prevents path traversal via crafted CSV fields like '../../etc/passwd'.
    """
    return bool(media_id and _SAFE_MEDIA_ID_RE.match(media_id))


def _safe_media_path(base_dir: str, filename: str) -> str | None:
    """Construct a media file path and verify it stays within base_dir.

    Returns None if the resolved path escapes the base directory.
    """
    candidate = os.path.join(base_dir, filename)
    resolved = Path(candidate).resolve()
    base_resolved = Path(base_dir).resolve()
    if not resolved.is_relative_to(base_resolved):
        log.warning(f"Path traversal blocked: {candidate} escapes {base_dir}")
        return None
    return str(resolved)


def _read_transcript(voice_dir: str, voice_id: str) -> str | None:
    """Look for a companion .txt transcript file for a voice recording.

    Transcript files are generated by Whisper and saved alongside audio:
      voice_<id>.txt  or  dream_<id>.txt
    """
    if not _is_safe_media_id(voice_id):
        log.warning(f"Unsafe voice_id rejected: {voice_id!r}")
        return None
    for prefix in ("voice_", "dream_"):
        txt_path = _safe_media_path(voice_dir, f"{prefix}{voice_id}.txt")
        if txt_path and os.path.isfile(txt_path):
            try:
                with open(txt_path, encoding="utf-8") as f:
                    text = f.read().strip()
                    return text if text else None
            except OSError:
                pass
    return None


def _extract_exif(photo_path: str) -> dict[str, Any]:
    """Extract EXIF metadata from a photo using Pillow.

    Returns dict with: width, height, file_size, lat, lon, taken_at, camera.
    """
    if not HAS_PILLOW or not os.path.isfile(photo_path):
        return {}

    metadata: dict[str, Any] = {}
    try:
        img = Image.open(photo_path)
        metadata["width"] = img.width
        metadata["height"] = img.height
        metadata["file_size_bytes"] = os.path.getsize(photo_path)

        exif = img._getexif() or {}  # type: ignore[attr-defined]
        for tag_id, value in exif.items():
            tag = TAGS.get(tag_id, tag_id)
            if tag == "GPSInfo":
                gps = {GPSTAGS.get(k, k): v for k, v in value.items()}
                lat = _convert_gps(
                    gps.get("GPSLatitude"), gps.get("GPSLatitudeRef")
                )
                lon = _convert_gps(
                    gps.get("GPSLongitude"), gps.get("GPSLongitudeRef")
                )
                if lat is not None:
                    metadata["lat"] = lat
                if lon is not None:
                    metadata["lon"] = lon
            elif tag == "DateTimeOriginal":
                metadata["taken_at"] = str(value)
            elif tag == "Model":
                metadata["camera"] = str(value)

        img.close()
    except Exception as e:
        log.debug(f"EXIF extraction failed for {photo_path}: {e}")

    return metadata


def _convert_gps(coords: Any, ref: Any) -> float | None:
    """Convert GPS EXIF coordinates to decimal degrees."""
    if not coords or not ref:
        return None
    try:
        degrees = float(coords[0])
        minutes = float(coords[1])
        seconds = float(coords[2])
        result = degrees + minutes / 60.0 + seconds / 3600.0
        if ref in ("S", "W"):
            result = -result
        return round(result, 6)
    except (TypeError, ValueError, IndexError):
        return None


def _get_video_info(video_path: str) -> dict[str, Any]:
    """Use ffprobe to extract video metadata: duration, resolution.

    The video_path must already be validated via _safe_media_path() before
    calling this function to prevent command injection via crafted paths.
    """
    if not os.path.isfile(video_path):
        return {}

    info = {}
    try:
        result = subprocess.run(
            [
                "ffprobe", "-v", "quiet",
                "-print_format", "json",
                "-show_format", "-show_streams",
                "--", video_path,
            ],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0:
            data = json.loads(result.stdout)
            fmt = data.get("format", {})
            info["duration_sec"] = round(float(fmt.get("duration", 0)), 1)
            info["file_size_bytes"] = int(fmt.get("size", 0))

            # Find video stream for resolution
            for stream in data.get("streams", []):
                if stream.get("codec_type") == "video":
                    info["width"] = stream.get("width")
                    info["height"] = stream.get("height")
                    info["codec"] = stream.get("codec_name")
                    break
    except (subprocess.TimeoutExpired, json.JSONDecodeError, OSError) as e:
        log.debug(f"ffprobe failed for {video_path}: {e}")

    return info


def parse_voice_meta(file_path: str) -> list[Event]:
    """Parse voice memo metadata CSV → media.voice events.

    Format: epoch,time,voice_id,duration_sec,location
    Looks for companion .txt transcript file alongside the audio.
    """
    events = []
    voice_dir = os.path.dirname(file_path)

    with open(file_path, encoding="utf-8", errors="replace") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            try:
                fields = line.split(",")
                if len(fields) < 3:
                    continue

                epoch_str = fields[0].strip()
                if not epoch_str.isdigit():
                    continue

                ts_utc, ts_local = parse_timestamp(epoch_str, DEFAULT_TZ_OFFSET)
                voice_id = fields[2].strip() if len(fields) > 2 else epoch_str
                duration = safe_float(fields[3]) if len(fields) > 3 else None
                location = fields[4].strip() if len(fields) > 4 else ""

                # Determine event type from file or directory context
                event_type = "memo"
                if "dream" in os.path.basename(file_path).lower():
                    event_type = "dream_journal"

                # Look for transcript
                transcript = _read_transcript(voice_dir, voice_id)

                extra: dict[str, Any] = {"voice_id": voice_id}
                if duration is not None:
                    extra["duration_sec"] = duration
                if location:
                    extra["location"] = location

                # Add transcript analysis if available
                if transcript:
                    extra["word_count"] = len(transcript.split())
                    vader = _get_vader()
                    if vader:
                        scores = vader.polarity_scores(transcript)
                        extra["sentiment"] = round(scores["compound"], 4)
                        extra["sentiment_detail"] = {
                            k: round(v, 3) for k, v in scores.items()
                        }

                events.append(Event(
                    timestamp_utc=ts_utc,
                    timestamp_local=ts_local,
                    timezone_offset=DEFAULT_TZ_OFFSET,
                    source_module="media.voice",
                    event_type=event_type,
                    value_numeric=duration,
                    value_text=transcript[:2000] if transcript else None,
                    value_json=safe_json(extra),
                    tags=f"media,voice,{event_type}",
                    confidence=1.0,
                    parser_version=PARSER_VERSION,
                ))

            except Exception as e:
                log.warning(f"{file_path}:{line_num}: voice parse error: {e}")
                continue

    return events


def parse_photo_meta(file_path: str) -> list[Event]:
    """Parse photo metadata CSV → media.photo events.

    Format: epoch,time,photo_id,category,location
    Extracts EXIF from companion photo file if available.
    """
    events = []
    photo_dir = os.path.dirname(file_path)

    with open(file_path, encoding="utf-8", errors="replace") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            try:
                fields = line.split(",")
                if len(fields) < 3:
                    continue

                epoch_str = fields[0].strip()
                if not epoch_str.isdigit():
                    continue

                ts_utc, ts_local = parse_timestamp(epoch_str, DEFAULT_TZ_OFFSET)
                photo_id = fields[2].strip() if len(fields) > 2 else epoch_str
                category = fields[3].strip() if len(fields) > 3 else "Other"
                location = fields[4].strip() if len(fields) > 4 else ""

                extra: dict[str, Any] = {"photo_id": photo_id, "category": category}
                if location:
                    extra["location"] = location

                # Try EXIF extraction from companion photo
                if _is_safe_media_id(photo_id):
                    for ext in (".jpg", ".jpeg", ".png", ".heic"):
                        photo_path = _safe_media_path(
                            photo_dir, f"photo_{photo_id}{ext}"
                        )
                        if photo_path and os.path.isfile(photo_path):
                            exif = _extract_exif(photo_path)
                            if exif:
                                extra["exif"] = exif
                            break

                event_type = "capture"
                if category.lower() == "document":
                    event_type = "document"

                events.append(Event(
                    timestamp_utc=ts_utc,
                    timestamp_local=ts_local,
                    timezone_offset=DEFAULT_TZ_OFFSET,
                    source_module="media.photo",
                    event_type=event_type,
                    value_text=category,
                    value_json=safe_json(extra),
                    tags=f"media,photo,{category.lower()}",
                    confidence=1.0,
                    parser_version=PARSER_VERSION,
                ))

            except Exception as e:
                log.warning(f"{file_path}:{line_num}: photo parse error: {e}")
                continue

    return events


def parse_video_meta(file_path: str) -> list[Event]:
    """Parse video metadata CSV → media.video events.

    Format: epoch,time,video_id,note
    Uses ffprobe for duration/resolution when video file exists.
    """
    events = []
    video_dir = os.path.dirname(file_path)

    with open(file_path, encoding="utf-8", errors="replace") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line:
                continue

            try:
                fields = line.split(",")
                if len(fields) < 2:
                    continue

                epoch_str = fields[0].strip()
                if not epoch_str.isdigit():
                    continue

                ts_utc, ts_local = parse_timestamp(epoch_str, DEFAULT_TZ_OFFSET)
                video_id = fields[2].strip() if len(fields) > 2 else epoch_str
                note = fields[3].strip() if len(fields) > 3 else ""

                extra: dict[str, Any] = {"video_id": video_id}
                if note:
                    extra["note"] = note

                # Try to get video info from companion file
                duration: float | None = None
                if _is_safe_media_id(video_id):
                    for ext in (".mp4", ".3gp", ".mkv", ".mov"):
                        video_path = _safe_media_path(
                            video_dir, f"video_{video_id}{ext}"
                        )
                        if video_path and os.path.isfile(video_path):
                            vinfo = _get_video_info(video_path)
                            if vinfo:
                                extra.update(vinfo)
                                duration = vinfo.get("duration_sec")
                            break

                events.append(Event(
                    timestamp_utc=ts_utc,
                    timestamp_local=ts_local,
                    timezone_offset=DEFAULT_TZ_OFFSET,
                    source_module="media.video",
                    event_type="clip",
                    value_numeric=duration,
                    value_text=note if note else None,
                    value_json=safe_json(extra),
                    tags="media,video",
                    confidence=1.0,
                    parser_version=PARSER_VERSION,
                ))

            except Exception as e:
                log.warning(f"{file_path}:{line_num}: video parse error: {e}")
                continue

    return events


# Parser registry: filename prefix → parser function
PARSER_REGISTRY = {
    "voice_meta_": parse_voice_meta,
    "photo_meta_": parse_photo_meta,
    "video_meta_": parse_video_meta,
}
